[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
todo_list_app = "AazuWKaA6pHEx2MnByjttPopotMC6VKqi7TghrQBGL4p"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/abhinawkumar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
