[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
todo_list_app = "3QXTFnnR1JbNcESqMQYvZ4pt7crQamifvm5g4TfmAG14"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/abhinawkumar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
